-- ----------------------------
-- Table structure for UserPingListTable
-- ----------------------------
CREATE TABLE [dbo].[temp] (
[id] bigint NOT NULL IDENTITY(1,1) ,
[userId] bigint NULL ,
[userName] varchar(255) NULL ,
[ipAddress] varchar(255) NULL ,
[clientIpAddress] varchar(255) NULL ,
[createTime] datetime NULL DEFAULT (getdate()) ,
[ping1] int NULL ,
[ping2] int NULL ,
[ping3] int NULL ,
[ping4] int NULL ,
[ping5] int NULL ,
[ping6] int NULL ,
[ping7] int NULL ,
[ping8] int NULL ,
[ping9] int NULL ,
[ping10] int NULL ,
[ping11] int NULL ,
[ping12] int NULL ,
[ping13] int NULL ,
[ping14] int NULL ,
[ping15] int NULL ,
[ping16] int NULL ,
[ping17] int NULL ,
[ping18] int NULL ,
[ping19] int NULL ,
[ping20] int NULL ,
[ping21] int NULL ,
[ping22] int NULL ,
[ping23] int NULL ,
[ping24] int NULL ,
[ping25] int NULL ,
[ping26] int NULL ,
[ping27] int NULL ,
[ping28] int NULL ,
[ping29] int NULL ,
[ping30] int NULL ,
[ping31] int NULL ,
[ping32] int NULL ,
[ping33] int NULL ,
[ping34] int NULL ,
[ping35] int NULL ,
[ping36] int NULL ,
[ping37] int NULL ,
[ping38] int NULL ,
[ping39] int NULL ,
[ping40] int NULL ,
[ping41] int NULL ,
[ping42] int NULL ,
[ping43] int NULL ,
[ping44] int NULL ,
[ping45] int NULL ,
[ping46] int NULL ,
[ping47] int NULL ,
[ping48] int NULL ,
[ping49] int NULL ,
[ping50] int NULL ,
[ping51] int NULL ,
[ping52] int NULL ,
[ping53] int NULL ,
[ping54] int NULL ,
[ping55] int NULL ,
[ping56] int NULL ,
[ping57] int NULL ,
[ping58] int NULL ,
[ping59] int NULL ,
[ping60] int NULL ,
[ping61] int NULL ,
[ping62] int NULL ,
[ping63] int NULL ,
[ping64] int NULL ,
[ping65] int NULL ,
[ping66] int NULL ,
[ping67] int NULL ,
[ping68] int NULL ,
[ping69] int NULL ,
[ping70] int NULL ,
[ping71] int NULL ,
[ping72] int NULL ,
[ping73] int NULL ,
[ping74] int NULL ,
[ping75] int NULL ,
[ping76] int NULL ,
[ping77] int NULL ,
[ping78] int NULL ,
[ping79] int NULL ,
[ping80] int NULL ,
[ping81] int NULL ,
[ping82] int NULL ,
[ping83] int NULL ,
[ping84] int NULL ,
[ping85] int NULL ,
[ping86] int NULL ,
[ping87] int NULL ,
[ping88] int NULL ,
[ping89] int NULL ,
[ping90] int NULL ,
[ping91] int NULL ,
[ping92] int NULL ,
[ping93] int NULL ,
[ping94] int NULL ,
[ping95] int NULL ,
[ping96] int NULL ,
[ping97] int NULL ,
[ping98] int NULL ,
[ping99] int NULL ,
[ping100] int NULL ,
[area] nvarchar(255) DEFAULT 'nowhere' ,
[city] nvarchar(255) NULL ,
[isp] nvarchar(255) DEFAULT 'unknown' ,
[valid_ping_count] int NULL ,
[avg_ping] float(53) NULL ,
[stdev_ping] float(53) NULL ,
PRIMARY KEY ([id])
)

-- ----------------------------
-- Indexes structure for table UserPingListTable
-- ----------------------------
CREATE INDEX [NCL_UserPingListTable_CreateTime] ON [dbo].[temp]
([createTime] DESC)

execute sp_rename 'temp', 'UserPingListTable'
